"""Step A vs Step B on the same clean, held-out test windows (spec §10)."""

from __future__ import annotations

import numpy as np
from sklearn.metrics import average_precision_score

from .datasets import HARD_NEGATIVES


def evaluate_method(scores, label, kind, threshold: float) -> dict:
    scores, label, kind = np.asarray(scores), np.asarray(label).astype(int), np.asarray(kind)
    pred = scores >= threshold
    tp = int(np.sum(pred & (label == 1)))
    fp = int(np.sum(pred & (label == 0)))
    fn = int(np.sum(~pred & (label == 1)))
    tn = int(np.sum(~pred & (label == 0)))
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    ap = float(average_precision_score(label, scores)) if 0 < label.sum() < label.size else 0.0
    negatives = label == 0
    return {
        "threshold": float(threshold),
        "precision": precision, "recall": recall, "f1": f1, "average_precision": ap,
        "confusion": {"tp": tp, "fn": fn, "fp": fp, "tn": tn},
        "false_positive_rate": fp / (fp + tn) if fp + tn else 0.0,
        "hard_negative_fpr": {
            k: float(np.mean(pred[negatives & (kind == k)]))
            for k in sorted(HARD_NEGATIVES) if np.any(negatives & (kind == k))
        },
        "recall_by_drone": {
            k: float(np.mean(pred[(label == 1) & (kind == k)]))
            for k in sorted({str(k) for k in kind[label == 1]})
        },
    }


def level_match(window: np.ndarray, target_db: float) -> np.ndarray:
    """Scale a window to a target RMS level (dBFS), clipped to [-1, 1]."""
    x = np.asarray(window, np.float64)
    level = 20 * np.log10(np.sqrt(np.mean(x**2)) + 1e-12)
    return np.clip(x * 10 ** ((target_db - level) / 20), -1, 1).astype(np.float32)


def results_markdown(
    results: dict[str, dict],
    windows: int,
    drone_windows: int,
    notes: list[str] | None = None,
    sections: list[str] | None = None,
) -> str:
    names = list(results)
    lines = [
        "# Step A vs Step B — held-out test results",
        "",
        "Generated by `make evaluate`. Test set: clean (never augmented) 0.975 s windows from "
        "DroneNoise flights and ESC-50 fold 5 that no model saw in training or validation. "
        f"{windows} windows, {drone_windows} of them drone.",
        "",
        "| Method | Threshold | Precision | Recall | F1 | Avg. precision | False-positive rate |",
        "|---|---|---|---|---|---|---|",
    ]
    for name in names:
        r = results[name]
        lines.append(
            f"| {name} | {r['threshold']:.3f} | {r['precision']:.3f} | {r['recall']:.3f} | "
            f"{r['f1']:.3f} | {r['average_precision']:.3f} | {r['false_positive_rate']:.3f} |"
        )
    lines += ["", "## Confusion matrices", "",
              "| Method | TP | FN | FP | TN |", "|---|---|---|---|---|"]
    for name in names:
        c = results[name]["confusion"]
        lines.append(f"| {name} | {c['tp']} | {c['fn']} | {c['fp']} | {c['tn']} |")
    kinds = sorted({k for r in results.values() for k in r["hard_negative_fpr"]})
    lines += ["", "## False-positive rate on hard negatives (drone-like sounds)", "",
              "| Sound | " + " | ".join(names) + " |", "|---" * (len(names) + 1) + "|"]
    for k in kinds:
        cells = " | ".join(f"{results[n]['hard_negative_fpr'].get(k, 0):.3f}" for n in names)
        lines.append(f"| {k} | {cells} |")
    drones = sorted({k for r in results.values() for k in r["recall_by_drone"]})
    lines += ["", "## Recall by drone type", "",
              "| Drone | " + " | ".join(names) + " |", "|---" * (len(names) + 1) + "|"]
    for k in drones:
        cells = " | ".join(f"{results[n]['recall_by_drone'].get(k, 0):.3f}" for n in names)
        lines.append(f"| {k} | {cells} |")
    for section in sections or []:
        lines += ["", section.rstrip()]
    if notes:
        lines += ["", "## Notes", ""] + [f"- {n}" for n in notes]
    return "\n".join(lines) + "\n"


def first_start_s(scores, threshold: float = 0.5) -> float | None:
    """Audio time at which the node's smoother would emit START for these window scores."""
    from kuulo_node.audio import HOP_S, WINDOW_SAMPLES
    from kuulo_protocol.models import Phase
    from kuulo_protocol.smoothing import DetectionSmoother, SmootherConfig

    smoother = DetectionSmoother(SmootherConfig(threshold=threshold))
    for i, score in enumerate(scores):
        if smoother.push(i * HOP_S, float(score)) is Phase.START:
            return i * HOP_S + WINDOW_SAMPLES / 16_000
    return None


def event_summary(rows) -> dict:
    """rows: (label, kind, first_start_s or None) per recording."""
    drone = [s for label, _, s in rows if label == 1]
    hits = [s for s in drone if s is not None]
    hard = [s for label, kind, s in rows if label == 0 and kind in HARD_NEGATIVES]
    other = [s for label, kind, s in rows if label == 0 and kind not in HARD_NEGATIVES]
    return {
        "drone_detected": len(hits), "drone_total": len(drone),
        "median_start_s": float(np.median(hits)) if hits else None,
        "max_start_s": float(max(hits)) if hits else None,
        "hard_false_starts": sum(s is not None for s in hard), "hard_total": len(hard),
        "other_false_starts": sum(s is not None for s in other), "other_total": len(other),
    }
