"""Step A vs Step B on the same clean, held-out test windows (spec §10)."""

from __future__ import annotations

import numpy as np
from sklearn.metrics import average_precision_score

from .datasets import HARD_NEGATIVES


def evaluate_method(scores, label, kind, threshold: float) -> dict:
    scores, label, kind = np.asarray(scores), np.asarray(label).astype(int), np.asarray(kind)
    pred = scores >= threshold
    tp = int(np.sum(pred & (label == 1)))
    fp = int(np.sum(pred & (label == 0)))
    fn = int(np.sum(~pred & (label == 1)))
    tn = int(np.sum(~pred & (label == 0)))
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    ap = float(average_precision_score(label, scores)) if 0 < label.sum() < label.size else 0.0
    negatives = label == 0
    return {
        "threshold": float(threshold),
        "precision": precision, "recall": recall, "f1": f1, "average_precision": ap,
        "confusion": {"tp": tp, "fn": fn, "fp": fp, "tn": tn},
        "false_positive_rate": fp / (fp + tn) if fp + tn else 0.0,
        "hard_negative_fpr": {
            k: float(np.mean(pred[negatives & (kind == k)]))
            for k in sorted(HARD_NEGATIVES) if np.any(negatives & (kind == k))
        },
        "recall_by_drone": {
            k: float(np.mean(pred[(label == 1) & (kind == k)]))
            for k in sorted({str(k) for k in kind[label == 1]})
        },
    }


def results_markdown(results: dict[str, dict], windows: int, drone_windows: int) -> str:
    names = list(results)
    lines = [
        "# Step A vs Step B — held-out test results",
        "",
        "Generated by `make evaluate`. Test set: clean (never augmented) 0.975 s windows from "
        "DroneNoise flights and ESC-50 fold 5 that no model saw in training or validation. "
        f"{windows} windows, {drone_windows} of them drone.",
        "",
        "| Method | Threshold | Precision | Recall | F1 | Avg. precision | False-positive rate |",
        "|---|---|---|---|---|---|---|",
    ]
    for name in names:
        r = results[name]
        lines.append(
            f"| {name} | {r['threshold']:.3f} | {r['precision']:.3f} | {r['recall']:.3f} | "
            f"{r['f1']:.3f} | {r['average_precision']:.3f} | {r['false_positive_rate']:.3f} |"
        )
    lines += ["", "## Confusion matrices", "",
              "| Method | TP | FN | FP | TN |", "|---|---|---|---|---|"]
    for name in names:
        c = results[name]["confusion"]
        lines.append(f"| {name} | {c['tp']} | {c['fn']} | {c['fp']} | {c['tn']} |")
    kinds = sorted({k for r in results.values() for k in r["hard_negative_fpr"]})
    lines += ["", "## False-positive rate on hard negatives (drone-like sounds)", "",
              "| Sound | " + " | ".join(names) + " |", "|---" * (len(names) + 1) + "|"]
    for k in kinds:
        cells = " | ".join(f"{results[n]['hard_negative_fpr'].get(k, 0):.3f}" for n in names)
        lines.append(f"| {k} | {cells} |")
    drones = sorted({k for r in results.values() for k in r["recall_by_drone"]})
    lines += ["", "## Recall by drone type", "",
              "| Drone | " + " | ".join(names) + " |", "|---" * (len(names) + 1) + "|"]
    for k in drones:
        cells = " | ".join(f"{results[n]['recall_by_drone'].get(k, 0):.3f}" for n in names)
        lines.append(f"| {k} | {cells} |")
    return "\n".join(lines) + "\n"
