/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CpuTempC = number | null;
export type MicOk = boolean;
export type NodeId = string;
export type QueueDepth = number;
export type SchemaVersion = "1.0";
export type SentAt = string;
export type Signature = string;
export type SoftwareVersion = string;
export type Late = boolean;
export type Status = "accepted" | "duplicate";
export type Data = Observation | Track | NodeView | null;
export type PeakFreqHz = number;
export type SnrDb = number;
export type BearingDeg = number | null;
export type Confidence = number;
export type Label = "drone_multirotor" | "drone_fixedwing_engine" | "aircraft" | "bird" | "unknown";
export type DetectionId = string;
export type Phase = "start" | "update" | "end";
export type ObservationId = string;
export type ObservedAt = string;
export type SchemaVersion1 = "1.0";
export type AccuracyM = number;
export type Lat = number;
export type Lon = number;
export type Signature1 = string;
export type Id = string;
export type SourceType =
  "acoustic_node" | "simulated_node" | "citizen_report" | "remote_id" | "adsb" | "external_network";
export type TimeQuality = "gps" | "ntp" | "manual";
export type Confidence1 = number;
export type FirstSeen = string;
export type LastSeen = string;
export type ObservationIds = string[];
export type Lat1 = number;
export type Lon1 = number;
export type SilentNeighbourIds = string[];
export type TrackStatus = "tentative" | "confirmed" | "downgraded" | "closed";
export type TrackId = string;
export type UncertaintyM = number;
export type HeadingDeg = number;
export type SpeedMps = number;
export type LastHeartbeatAt = string | null;
export type MicOk1 = boolean | null;
export type NodeId1 = string;
export type SoftwareVersion1 = string | null;
export type NodeStatus = "online" | "stale" | "offline";
export type UncorroboratedRate24H = number | null;
export type Type = "observation" | "track" | "node_status" | "resync";
export type NodeId2 = string;
export type PublicKey = string;
export type Observations = Observation[];
export type SilentNeighbours = NodeView[];

export interface KuuloSchema {
  Heartbeat?: Heartbeat;
  IngestResult?: IngestResult;
  LiveEvent?: LiveEvent;
  NodeRegistration?: NodeRegistration;
  NodeView?: NodeView;
  Observation?: Observation;
  Track?: Track;
  TrackDetail?: TrackDetail;
}
/**
 * A node saying it is alive, so silence can be told apart from failure.
 */
export interface Heartbeat {
  cpu_temp_c?: CpuTempC;
  mic_ok: MicOk;
  node_id: NodeId;
  queue_depth: QueueDepth;
  schema_version?: SchemaVersion;
  sent_at: SentAt;
  signature?: Signature;
  software_version: SoftwareVersion;
}
export interface IngestResult {
  late?: Late;
  status: Status;
}
/**
 * One message on the /v1/live WebSocket. `resync` tells the client to reload its snapshot.
 */
export interface LiveEvent {
  data?: Data;
  type: Type;
}
/**
 * A source noticed something. Used by every source type.
 */
export interface Observation {
  acoustic?: Acoustic | null;
  detection: Detection;
  event: EventRef;
  observation_id?: ObservationId;
  observed_at: ObservedAt;
  schema_version?: SchemaVersion1;
  sensor_location: SensorLocation;
  signature?: Signature1;
  source: Source;
  time_quality: TimeQuality;
}
export interface Acoustic {
  peak_freq_hz: PeakFreqHz;
  snr_db: SnrDb;
}
export interface Detection {
  bearing_deg?: BearingDeg;
  confidence: Confidence;
  label: Label;
}
export interface EventRef {
  detection_id: DetectionId;
  phase: Phase;
}
export interface SensorLocation {
  accuracy_m: AccuracyM;
  lat: Lat;
  lon: Lon;
}
export interface Source {
  id: Id;
  type: SourceType;
}
/**
 * The server's belief that a drone is at a place, with its evidence.
 */
export interface Track {
  confidence: Confidence1;
  first_seen: FirstSeen;
  label: Label;
  last_seen: LastSeen;
  observation_ids: ObservationIds;
  position: GeoPoint;
  silent_neighbour_ids: SilentNeighbourIds;
  status: TrackStatus;
  track_id: TrackId;
  uncertainty_m: UncertaintyM;
  velocity?: Velocity | null;
}
export interface GeoPoint {
  lat: Lat1;
  lon: Lon1;
}
export interface Velocity {
  heading_deg: HeadingDeg;
  speed_mps: SpeedMps;
}
export interface NodeView {
  last_heartbeat_at?: LastHeartbeatAt;
  location: SensorLocation;
  mic_ok?: MicOk1;
  node_id: NodeId1;
  software_version?: SoftwareVersion1;
  status: NodeStatus;
  time_quality: TimeQuality;
  uncorroborated_rate_24h?: UncorroboratedRate24H;
}
export interface NodeRegistration {
  location: SensorLocation;
  node_id: NodeId2;
  public_key: PublicKey;
  time_quality: TimeQuality;
}
export interface TrackDetail {
  observations: Observations;
  silent_neighbours: SilentNeighbours;
  track: Track;
}
